export const TODO_ERROR_CODE = {
  NOT_FOUND: 'TODO_NOT_FOUND',
  TITLE_REQUIRED: 'TODO_TITLE_REQUIRED',
  INVALID_DUE_DATE: 'TODO_INVALID_DUE_DATE',
  INVALID_CATEGORY: 'TODO_INVALID_CATEGORY',
  INVALID_TAG: 'TODO_INVALID_TAG',
  TOO_MANY_TAGS: 'TODO_TOO_MANY_TAGS',
} as const;

export const TODO_VALIDATION = {
  TITLE_MAX_LENGTH: 180,
  DESCRIPTION_MAX_LENGTH: 2_000,
  TAG_MAX_LENGTH: 32,
  TAG_MAX_COUNT: 10,
  SEARCH_MAX_LENGTH: 180,
} as const;

export enum TodoStatusFilter {
  ALL = 'ALL',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
}

export enum TodoSort {
  CREATED_AT_DESC = 'CREATED_AT_DESC',
  CREATED_AT_ASC = 'CREATED_AT_ASC',
  DUE_ON_ASC = 'DUE_ON_ASC',
  DUE_ON_DESC = 'DUE_ON_DESC',
  PRIORITY_DESC = 'PRIORITY_DESC',
  PRIORITY_ASC = 'PRIORITY_ASC',
  TITLE_ASC = 'TITLE_ASC',
  TITLE_DESC = 'TITLE_DESC',
}
