export const TASK_ERROR_CODE = {
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',
  TASK_NOT_ASSIGNABLE: 'TASK_NOT_ASSIGNABLE',
  TASK_ALREADY_ASSIGNED: 'TASK_ALREADY_ASSIGNED',
  TASK_NOT_STARTABLE: 'TASK_NOT_STARTABLE',
  MEMBER_NOT_ELIGIBLE_FOR_TASK: 'MEMBER_NOT_ELIGIBLE_FOR_TASK',
  MEMBER_NOT_TASK_ASSIGNEE: 'MEMBER_NOT_TASK_ASSIGNEE',
  INVALID_TASK_TRANSITION: 'INVALID_TASK_TRANSITION',
  TASK_INVALID_STATUS_TRANSITION: 'TASK_INVALID_STATUS_TRANSITION',
  TASK_ALREADY_COMPLETED: 'TASK_ALREADY_COMPLETED',
  TASK_DIRECT_COMPLETION_NOT_ALLOWED: 'TASK_DIRECT_COMPLETION_NOT_ALLOWED',
  TASK_DIRECT_COMPLETION_REQUIRED: 'TASK_DIRECT_COMPLETION_REQUIRED',
  TASK_NOT_RESPONSIBLE: 'TASK_NOT_RESPONSIBLE',
  RESPONSIBLE_USER_NOT_ELIGIBLE: 'RESPONSIBLE_USER_NOT_ELIGIBLE',
  TASK_RECURRENCE_NOT_FOUND: 'TASK_RECURRENCE_NOT_FOUND',
  INVALID_TASK_RECURRENCE: 'INVALID_TASK_RECURRENCE',
  ATTACHMENT_LIMIT_REACHED: 'ATTACHMENT_LIMIT_REACHED',
  TASK_ATTACHMENTS_NOT_EDITABLE: 'TASK_ATTACHMENTS_NOT_EDITABLE',
} as const;

export const TASK_ACTIVITY = {
  TASK_CREATED: 'TASK_CREATED',
  TASK_ASSIGNED: 'TASK_ASSIGNED',
  TASK_STARTED: 'TASK_STARTED',
  TASK_ATTACHMENTS_ADDED: 'TASK_ATTACHMENTS_ADDED',
  TASK_ATTACHMENT_REMOVED: 'TASK_ATTACHMENT_REMOVED',
  TASK_RESPONSIBILITY_ASSIGNED: 'TASK_RESPONSIBILITY_ASSIGNED',
  TASK_RESPONSIBILITY_CHANGED: 'TASK_RESPONSIBILITY_CHANGED',
  TASK_RECURRENCE_CREATED: 'TASK_RECURRENCE_CREATED',
  TASK_RECURRENCE_UPDATED: 'TASK_RECURRENCE_UPDATED',
  TASK_RECURRENCE_PAUSED: 'TASK_RECURRENCE_PAUSED',
  TASK_RECURRENCE_RESUMED: 'TASK_RECURRENCE_RESUMED',
  TASK_RECURRENCE_BLOCKED: 'TASK_RECURRENCE_BLOCKED',
  TASK_OCCURRENCE_GENERATED: 'TASK_OCCURRENCE_GENERATED',
  TASK_REMINDER_SENT: 'TASK_REMINDER_SENT',
  TASK_COMPLETED_DIRECT: 'TASK_COMPLETED_DIRECT',
} as const;

export const TASK_NOTIFICATION = {
  TASK_ASSIGNED: 'TASK_ASSIGNED',
  TASK_REMINDER: 'TASK_REMINDER',
  TASK_RECURRENCE_BLOCKED: 'TASK_RECURRENCE_BLOCKED',
} as const;

export enum TaskSort {
  CREATED_AT_DESC = 'CREATED_AT_DESC',
  CREATED_AT_ASC = 'CREATED_AT_ASC',
  DUE_AT_ASC = 'DUE_AT_ASC',
  DUE_AT_DESC = 'DUE_AT_DESC',
  PRIORITY_DESC = 'PRIORITY_DESC',
  PRIORITY_ASC = 'PRIORITY_ASC',
}
